Revert to 2021 edition
Demanding 2024 edition is a breaking change that I'm not ready to impose
on existing users.

Here is the error message that they see:

```
  Downloaded ratelim v0.2.0
error: failed to parse manifest at `/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratelim-0.2.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0-nightly (bc89bffa5 2024-06-22)).
  Consider trying a more recent nightly release.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```